### ISSUE TITLE
Uninstallable due to auth-source dep

### ISSUE THREAD

**Issue by ieure** [fasheng/elfeed-protocol#12]
I'm not sure what's up with this, but if I try to install elfeed-protocol 20181117.1159, I get the error:

```
package-compute-transaction: Package ‘auth-source-0’ is unavailable
```

Also, package-lint 0.6 reports an error on that line:

```
7:1: error: Expected (package-name "version-num"), but found auth-source.
```

It looks like auth-source has been bundled with Emacs since at least 23.1, so I'd expect the Emacs 24.4 dep to satisfy the requirement.  Removing the dep, then installing the files with `package-install-from-buffer` seems to work fine.

I'm using Emacs 25.2.1.  Maybe this behavior changed in Emacs 26.x.

**Comment by fasheng** [comment]
Thanks your notice, I removed `auth-source` from Package-Requires just now. It should works.
