### ISSUE TITLE
Owncloud News folders as tags

### ISSUE THREAD

**Issue by benneti** [fasheng/elfeed-protocol#15]
Would it be possible to use the owncloud news folders to sort the feeds in elfeed?

**Comment by fasheng** [comment]
I use elfeed-org to set autotags, you could have a try  like the example in README did.

And about the elfeed sort strategy, I have not much idea, but I add a new "<" keybinding myself to filter special feed easily, hope it helps:
https://github.com/skeeto/elfeed/pull/244

**Comment by benneti** [comment]
Thanks for the reply.
I think I do not fully comprehend how to set this up, I added this
```
(defadvice elfeed (after configure-elfeed-feeds activate)
  "Make elfeed-org autotags rules works with elfeed-protocol."
  (setq elfeed-protocol-tags elfeed-feeds)
  (setq elfeed-feeds (list
                      (list "owncloud+https://benneti@URL"
                            :password '(password-store-get "URL/benneti")
                            :autotags elfeed-protocol-tags))))
```
To my init.el then I exportet an opml file of elfeed and imported it to an elfeed.org file which I load with elfeed-org.
The file looks like this
```
* Imported Feeds            :elfeed:
** [[owncloud+https://benneti@URL/nextcloud][]]
```
Is this the code the example you meant and if yes do you have another pointer how to go from here because I do not see any difference to before.

**Comment by fasheng** [comment]
The feed url in elfeed.org should not start with "owncloud+https…", its just the normal feed url format.

I always use elfeed-org to manage feeds and export opml to owncloud, and you could export from owncloud then import by elfeed-org, too.

Once elfeed-org works, you will see the :aututags value in "elfeed-feeds" variable after elfeed shown. And the autotags only added to the new entiries.

**Comment by benneti** [comment]
Thank you, I think I will take some time to get elfeed-org working.
If you think this makes it possible to tag the different feeds in one nextcloud instance, I think you can close the issue.

**Comment by fasheng** [comment]
It do works, I use owncloud news and elfeed-org every day, just enjoy!

**Comment by benneti** [comment]
Great I got it working by enclosing the code from the readme with an 
`(with-eval-after-load 'elfeed ...)` -- I think before it loaded the packages in the wrong direction which made it impossible to load the right autotags.
