### ISSUE TITLE
NewsBlur elfeed-curl--call-callback error.

### ISSUE THREAD

**Issue by peng051410** [fasheng/elfeed-protocol#16]
I use newsblur as my protocol. got errors:
`Error running timer ‘elfeed-curl--call-callback’: (wrong-type-argument stringp ((("http://kailing.pub") ("http://www.ruanyifeng.com/blog/atom.xml") ;`
What should i do ?

**Comment by fasheng** [comment]
Works fine here with `Emacs 26.1`, `elfeed 3.1.0`, `elfeed-protocol 0.5.8` on linux with the following config:
```lisp
(setq elfeed-db-directory "/tmp/elfeed")
(setq elfeed-protocol-newsblur-maxpages 5)
;; setup cookie file for newsblur
(setq elfeed-curl-extra-arguments '("-c" "/tmp/newsblur-cookie"
                                    "-b" "/tmp/newsblur-cookie"))
(setq elfeed-feeds '(("newsblur+https://user@newsblur.com"
                      :password "password")))
(setq elfeed-log-level 'debug)
(elfeed-set-timeout 36000)
(elfeed-protocol-enable)
```
You could `toggle-debug-on-error` before update operation and post message in `*elfeed-log*` with debug level to find more information.

**Comment by peng051410** [comment]
Works for me! Thanks.
