### ISSUE TITLE
owncloud update error

### ISSUE THREAD

**Issue by muralikodali** [fasheng/elfeed-protocol#18]
I have recently updated my emacs from version 25.3 to 26.2 .
I fetch my feeds from nextcloud server.

it is giving following debug info:

Debugger entered--Lisp error: (wrong-type-argument elfeed-feed #s(elfeed-feed :id "owncloud+http://user@192.168.1.11/nextcloud::http://feeds.feedburner.com/Command-line-fu" :url "owncloud+http://user@192.168.1.11/nextcloud::http://feeds.feedburner.com/Command-line-fu" :title "All commands" :author nil :meta nil))
  signal(wrong-type-argument (elfeed-feed #s(elfeed-feed :id "owncloud+http://user@192.168.1.11/nextcloud::http://feeds.feedburner.com/Command-line-fu" :url "owncloud+http://user@192.168.1.11/nextcloud::http://feeds.feedburner.com/Command-line-fu" :title "All commands" :author nil :meta nil)))
  elfeed-protocol-owncloud--parse-feeds("http://user:password@192.168.1.11/nextcloud")
  #f(compiled-function (status) #<bytecode 0x2d9add5>)(t)
  #f(compiled-function (status) #<bytecode 0x542b59>)(t)
  #f(compiled-function () #<bytecode 0x1e30269>)()
  elfeed-curl--call-callback(#<buffer  *curl*> 0 "http://192.168.1.11/nextcloud/index.php/apps/news/api/v1-2/feeds" #f(compiled-function (status) #<bytecode 0x542b59>))
  timer-event-handler([t 23749 47063 960234 nil elfeed-curl--call-callback (#<buffer  *curl*> 0 "http://192.168.1.11/nextcloud/index.php/apps/news/api/v1-2/feeds" #f(compiled-function (status) #<bytecode 0x542b59>)) nil 373000])

**Comment by fasheng** [comment]
Thanks for your report, I don't use emacs 26.2 yet, and will try to reproduce it later.

**Comment by fasheng** [comment]
Hi, everything is fine here after switching to emacs 26.2, and elfeed is 3.1.0, elfeed-protocol is 0.5.9.

And not sure if your problem is caused by the new database index format after emacs 26, you could have a look at the elfeed changelog:
https://github.com/skeeto/elfeed/blob/master/NEWS.md#300-2018-05-13

**Comment by muralikodali** [comment]
Thanks for your suggestion.
I have deleted database . After that i have passed commands elfeed-protocol-enable , elfeed-protocol-owncloud-update and updated feeds afterwards.
Now elfeed is working fine.
