### ISSUE TITLE
在Emacs 26.3上不工作

### ISSUE THREAD

**Issue by netlsd** [fasheng/elfeed-protocol#19]
我在emacs上配置了tt-rss, 调用elfeed-update, 在mini-buffer上显示"Wrong type argument: stringp, nil", 我打开debug模式，显示信息是:
[2019-12-05 20:59:43] [info]: Elfeed update: December  5 2019 20:59:43 CST
[2019-12-05 20:59:43] [debug]: elfeed-protocol-ttrss: login
除此之外，就没有任何信息了。我的tt-rss版本是19.8。

**Comment by fasheng** [comment]
应该和emacs版本无关，ttrss 19.8没有测试过，不知道接口是否作了变更，搜索了下没有看到对应的changelog。
可以的话你先在本地利用docker搭建18.12的测试环境，看能否成功，还可以启动emacs后先执行`(toggle-debug-on-error)` 以打印更多的错误信息。明天我有时间就尝试修复。
https://github.com/fasheng/elfeed-protocol/issues/13#issuecomment-453362612

**Comment by netlsd** [comment]
是的，我又检查一次，是我密码的问题，因为我的密码最后一位是/，程序可能把后面网址当成了一个参数导致了出错。谢谢你的工作，这个实在是太棒了。

**Comment by fasheng** [comment]
特殊格式的密码可以使用下面的格式:
```emacs-lisp
;; format 2, for password with special characters
("ttrss+https://user2@myhost.com"
  :password "password/with|special@characters:")
```
不谢，有问题可以随时提，那先关闭了。
