### ISSUE TITLE
[Feature Request] - Support the Fever API

### ISSUE THREAD

**Issue by vxid** [fasheng/elfeed-protocol#20]
First of all, thanks a lot for this package, it works very well with my current tt-rss setup.

I am considering switching to [miniflux](https://miniflux.app/) which uses the [fever API](https://feedafever.com/api) to sync articles. Other readers such as [FreshRSS](https://freshrss.org/) (and probably many more) also use it.

Now I have very limited knowledge in both Elisp and RSS so it is hard to estimate the amount of work this would take, but that would definitely be a great feature to have since it would allow elfeed to sync with a lot of feed readers through a standard-ish API.

**Comment by fasheng** [comment]
Fine, I'd like to implement it after Chinese New Year :)

**Comment by vxid** [comment]
Awesome. Happy new year to you in advance!

**Comment by fasheng** [comment]
Hi, fever protocol existed in latest elfeed-protocol 0.7.2, please have a try and reopen the issue if any problem occurs ;)

Here is example config, enjoy!
```emacs-lisp
(setq elfeed-feeds (list
                    (list "fever+https://user@myhost.com"
                          :api-url "https://myhost.com/plugins/fever/"
                          :password "password/with|special@characters:"
                          :autotags '(("example.com" comic)))))
```

**Comment by vxid** [comment]
@fasheng, I just tried the Fever integration and it works absolutely flawlessly with miniflux.
Thanks a lot, this is awesome!
