### ISSUE TITLE
[Feature Request] DecSync protocol support

### ISSUE THREAD

**Issue by jumper047** [fasheng/elfeed-protocol#22]
Hi!
There is interesting project [DecSync](https://github.com/39aldo39/DecSync) - protocol designed to use alongside with some folder synchronisation software. So via it user can sync their rss client via syncthing folder for example. Main advantage - there is no server needed. Author already create android app. Is it possible to implement this protocol support in your plugin?

**Comment by fasheng** [comment]
Thanks your advice, I'd like to learn about DecSync later and try to implement it if possible. And now I have to focus on events about 2019-nCoV in China. Best wishes!

**Comment by jumper047** [comment]
Ohh, man, good luck! Hope you'll be fine!

**Comment by fasheng** [comment]
Thanks to the help of traditional Chinese medicine, we believe the epidemic will soon be under control!

And I focus the issues and implemented fever protocol recent days. How ever, DecSync is a little different, it not provide restful API and there is no library code to parse the files in Emacs. So I decided not to implement this function for the time being.

Thanks your advice again~
