### ISSUE TITLE
Batch sync of read states

### ISSUE THREAD

**Issue by ieure** [fasheng/elfeed-protocol#23]
One thing I found somewhat surprising about elfeed-protocol is that when an item's read state is changed, it performs a synchronous request to Nextcloud to set it.  This is in contrast to other RSS syncing setups I've used, where changes of this nature are buffered locally, then sent in a batch when synchronizing.

The synchronous mechanism has some undesirable (at least to me) side-effects:

 - With my Nextcloud password stored in `pass(1)`, the GPG agent periodically clears its cache, which requires entering the passphrase at inconvenient times, like when browsing an entry's URL.
 - Subsequently, I moved to a setup where my private key is offline, stored on a Yubikey.  While this is more secure, it's significantly slower -- which translates to significant lag when browsing or marking entries as read.

On the one hand, "doctor, it hurts when I do this," but on the other hand, it's always struck me as unusual that marking as read/unread is a sync request.

What do you think about buffering read/unread/starred/unstarred and updating them all at once when `elfeed-search-fetch` is called?

**Comment by fasheng** [comment]
Thanks your advice, I will consider to implement it in following releases.

**Comment by fasheng** [comment]
Hi, you could enable the feature in latest elfeed-protocol 0.7.2, please have a try and reopen the issue if any problem occurs ;)

```emacs-lisp
(setq elfeed-protocol-lazy-sync t)
```

**Comment by ieure** [comment]
Thank you!  I updated yesterday and it's great, exactly what I wanted.
