### ISSUE TITLE
Error: ‘add-to-list’ can’t use lexical var

### ISSUE THREAD

**Issue by jtecca** [fasheng/elfeed-protocol#25]
- OS version: `macOS 10.14`
- emacs version: `26.3`
- elfeed version: `20200209.1942`
- elfeed-protocol version: `20200220.932`
- server version: `???` (docker image and tag)
- is variable `elfeed-protocol-xxx-feeds` empty: `yes`

This is a compile error shown in `*Compile-Log*` after upgrading via `package.el` so I haven't even executed `elfeed` yet.  I actually don't make use of this package on this particular computer, but it looks like something that was introduced recently.

**error backtrace**

```
In elfeed-protocol-append-pending-ids:
elfeed-protocol-common.el:261:17:Error: ‘add-to-list’ can’t use lexical var
    ‘pending-ids’; use ‘push’ or ‘cl-pushnew’
```

**Comment by jtecca** [comment]
I updated the PR with a machine that actually uses `elfeed-protocol` and it looks like the function swap from `add-to-list` to `push` works on emacs 27.

**Comment by fasheng** [comment]
Belive me, `(push 'pending-ids id t)` just report compile error:
```
In toplevel form:
elfeed-protocol-common.el:255:1:Error: Wrong number of arguments: (2 . 2), 3
```
If you installed [Cask](https://github.com/cask/cask), you could test it with commands, too:
```
make CASK=~/.cask/bin/cask init
make CASK=~/.cask/bin/cask build
```

And `push` will insert item even if already exists, so I prefer to use `cl-pushnew`.

**Comment by jtecca** [comment]
Thanks for the feedback and the note on how to test.  I am happy to update the PR to use `cl-pushnew` instead.

**Comment by fasheng** [comment]
Thanks, your PR merged now~
