### ISSUE TITLE
Malformed feeds

### ISSUE THREAD

**Issue by goodevilgenius** [fasheng/elfeed-protocol#29]
I tried to use elfeed with TT-RSS, following as well as I could the instructions in the README.

My `elfeed-feeds` is:

```lisp
  (setq elfeed-feeds
        '(
          ("ttrss+https://user@example.com"
           :password "my password")
          )
        )
```

But, when I run `elfeed-update` I get the error:

```
elfeed-feeds malformed, bad entry: ("ttrss+https://user@example.com" :password "my password")
```

- OS version: Linux 5.3.0
- emacs version: 26.3
- elfeed version: 3.3.0
- elfeed-protocol version: 0.3.2
- curl version: 7.58.0
- is variable `elfeed-protocol-ttrss-feeds` empty: no

**elfeed-log**

```
[2020-04-20 14:06:22] [info]: Elfeed update: April 20 2020 14:06:22 CDT
```

Please collect logs in buffer `*elfeed-log*` with the following config
before reporting issues:

```emacs-lisp
(setq elfeed-log-level 'debug)
(toggle-debug-on-error)

;; for more logs
(setq elfeed-protocol-log-trace t)
(setq elfeed-protocol-owncloud-maxsize 10)
(setq elfeed-protocol-ttrss-maxsize 10)
(setq elfeed-protocol-newsblur-maxpages 1)
```

**Comment by fasheng** [comment]
Hi, I guess you missed `(elfeed-protocol-enable)` in your config ;)

**Comment by goodevilgenius** [comment]
That was it. I didn't see that part.
Thanks!
