### ISSUE TITLE
Unable to retrieve feeds from Nextcloud

### ISSUE THREAD

**Issue by aancel** [fasheng/elfeed-protocol#30]
Hello,

Regarding the required information:
- OS version: `Manjaro`
- emacs version: `28.0.50 @ 4819bea6900348f923e0de58995ec41760993b6c`
- elfeed version: `3.3.0`
- elfeed-protocol version: `elfeed-protocol-20200422.624`
- curl version: `7.69.1`
- server version: `Nextcloud 18.0.4` and `News 14.1.4`
- is variable `elfeed-protocol-xxx-feeds` empty: `no`

**elfeed-log**

Please collect logs in buffer `*elfeed-log*` with the following config
before reporting issues:

```emacs-lisp
(setq elfeed-log-level 'debug)
(toggle-debug-on-error)

;; for more logs
(setq elfeed-protocol-log-trace t)
(setq elfeed-protocol-owncloud-maxsize 10)
(setq elfeed-protocol-ttrss-maxsize 10)
(setq elfeed-protocol-newsblur-maxpages 1)
```

**error backtrace**

```
None
```

I'm unable to get the articles from my Nextcloud instance with the following configuration:
```emacs-lisp
(use-package elfeed-protocol
    :after elfeed
    :ensure t
    :config
        ;; curl recommend
        (setq elfeed-use-curl t)
        (elfeed-set-timeout 36000)

        (setq elfeed-feeds '(
            ("owncloud+https://user@nextcloud.domain.com" :use-authinfo t)
        ))

        (setq elfeed-protocol-owncloud-maxsize 1000)
        (setq elfeed-protocol-owncloud-update-with-modified-time t)

        (setq elfeed-protocol-lazy-sync t)

        ;; Debug mode
        (setq elfeed-log-level 'debug)
        ;; (toggle-debug-on-error)

        ;; enable elfeed-protocol
        (elfeed-protocol-enable)
)
```

I'm using `auth-source-pass` for authentication via auth-source.
When I issue the `elfeed-protocol-owncloud-update` command, I am asked about the `Protocol feed:` which matches the url specified in elfeed feeds. Then the auth-source search is performed and ends up with a matching entry:
```
auth-source-pass: return (:host nextcloud.domain.com :port 443 :user user) as final result (plus hidden password)
auth-source-search: found 1 results (max 1) matching (:host "nextcloud.domain.com" :port 443 :user "user")
```
But then nothing happens and no feed seems to be downloaded. I've also attempted to use other forms to provide the password, like with `:password` but I end up in the same state.

Did I miss something in my configuration ?
Is there something I could try to solve this issue ?

Thanks fo the help !

**Comment by aancel** [comment]
Ok an update on this, it might come from my Nextcloud instance, I'm getting the following lines in the `*elfeed-log*` buffer:
```
[2020-04-26 11:43:26] [debug]: retrieve (https://user@nextcloud.domain.com/index.php/apps/news/api/v1-2/feeds)
[2020-04-26 11:43:26] [error]: https://user@nextcloud.domain.com/index.php/apps/news/api/v1-2/feeds: "(92) Unknown curl error!"
```

**Comment by fasheng** [comment]
Looks your configuration is correct. However your elfeed log format is a little strange, it should be something like`[debug]: retrieve (https://nextcloud.domain.com/index.php/apps/news/api/v1-2/feeds)`, do you replace it and prefix with `user@` manually?

And the `(92) Unknown curl error!` give us some information, could you let Nextcloud News app work in mobile phone?

**Comment by aancel** [comment]
However directly using curl seems to work !
I am able to get the feeds list with:
```
curl https://user:$(pass nextcloud-entry)@nextcloud.domain.com/index.php/apps/news/api/v1-2/feeds
```

**Comment by aancel** [comment]
Regarding the log format, the user is indeed present in the log output and I didn't manually add it (I've just replaced it with a generic "user")

Yes, I am successfully using Nextcloud News on my phone and it works fine !

**Comment by fasheng** [comment]
I see, please try to catch the curl command line with `ps aux | grep curl` once the update operation started. Let's see what it looks like(your could replace the secret field manually, such as the `Authorization` header).

**Comment by aancel** [comment]
I did try but the operation ends up too quickly for me to catch it.    
Could there be a way to redefine an elfeed-protocol function to print the command that is used ?

**Comment by fasheng** [comment]
You could redefine `elfeed-curl-retrieve` and print some logs before in somepalce:
```
(elfeed-log 'debug "CURL: %s %s" elfeed-curl-program-name args)
```

**Comment by aancel** [comment]
Ok I've used:
```
(elfeed-log 'error "CURL: %s %s %s %s %s" elfeed-curl-program-name url cb headers method data)
```
And got this log:
```
[2020-04-26 12:27:16] [error]: CURL: curl (https://user@nextcloud.domain.com/index.php/apps/news/api/v1-2/feeds) (#[redacted [nil https://user@nextcloud.domain.com 0 -1 t https://user@nextcloud.domain.com/index.php/apps/news/api/v1-2/feeds elfeed-is-status-error t elfeed-handle-http-error elfeed-move-to-first-empty-line set-buffer-multibyte elfeed-log debug elfeed-protocol-owncloud: %s buffer-string elfeed-protocol-owncloud--parse-feeds 0 elfeed-protocol-owncloud--do-update update-since-time update-since-id init nil kill-buffer print-escape-newlines elfeed-curl-error-message elfeed-protocol-log-trace elfeed-protocol-owncloud-update-with-modified-time] 6 

(fn STATUS)] elfeed-curl-queue-active elfeed-curl--run-queue] 3 

(fn STATUS)]) ((Authorization . Basic auth-string) (User-Agent . Emacs Elfeed 3.3.0)) nil
```

I've just redacted the user names, domain and auth strings, but username is indeed present in the url used by curl.

**Comment by fasheng** [comment]
Thanks, the user name is not the point. And tried my `nextcloud 18.0.1, News 14.1.3` just now, it works fine like before. I will try again after nextcloud updated to your version later.

Beside, you could print `args` directly and rebuild the command line and try if it works in console.

**Comment by aancel** [comment]
Ok, I've used the proper elfeed log you mentioned previously and I got:
```
curl --disable --compressed --silent --location -w(=~|jfeq6s^|NrF@FPqxjo= . %{size_header}) -m36000 -D- -HAuthorization: Basic token-part1
token-part2 -HUser-Agent: Emacs Elfeed 3.3.0 https://user@nextcloud.domain.com/index.php/apps/news/api/v1-2/feeds
```
Some remarks:
- The token seems to be split on two lines, I don't know if it is a print issue
- None of the -H options seems to be quoted (I don't know if it is an issue for the command)

Issuing the following command on the terminal does in fact work:
```
curl --disable --compressed --silent --location -m36000 -D- -H"Authorization: Basic token" -H"User-Agent: Emacs Elfeed 3.3.0" https://user@nextcloud.domain.com/index.php/apps/news/api/v1-2/feeds
```
(I've removed the -w option as I don't have the proper value)

**Comment by fasheng** [comment]
`nextcloud 18.0.4, News 14.1.4` works for me, too. So I guess it may be related with `emacs 28.0.50`, I just use `emacs 26.3`, someone reported strange issue about 28.0.50 before.

You could try if elfeed works as normal without elfeed-protocol, and try if elfeed-protocol works with older emacs version if possible.

**Comment by aancel** [comment]
I have tried using elfeed by filling the elfeed-feeds variable with urls and it seems to be working fine.    
I'll continue investigating.

**Comment by aancel** [comment]
Ok, I've cloned the repo to use as a source for the package.    
I've toyed a bit with the different functions and when I updated the `elfeed-protocol-owncloud--init-header` function, the feeds were retrieved.

Here is what I've changed:
```diff
-            ,(concat "Basic " (base64-encode-string
-                               (concat user ":" password))))
+            ,(replace-regexp-in-string "[\t\r\n]*" "" (concat "Basic " (base64-encode-string
+                               (concat user ":" password)))))
```

The line feed in my auth token was bugging me, so that is what I've tried.    
I need to do more tests to ensure that it really comes from that.    
I'll keep you in touch !

**Comment by aancel** [comment]
Ok, it seems to be confirmed as a fix on my side !    
I only kept this modification, cleaned up the elfeed database, resynchronized the feeds and it still seems to be working.    
Would you agree with this kind of fix ? (I find it pretty hacky and would like to know why there is a line feed inserted)    
Then, do you want to push it directly or do you want me to make a PR for it ?

**Comment by fasheng** [comment]
Great! And I found there is an optional argument to remove the line breaks in `base64-encode-string`, I have push a commit to fix it, please test the latest code then I will make a tag for it :)
```elisp
(base64-encode-string STRING &optional NO-LINE-BREAK)
```
BTW: The optional argument NO-LINE-BREAK is a little unreasonable...

**Comment by aancel** [comment]
Ok, I've updated to the last version you pushed, cleaned up elfeed, tested again and it works ! :)    
I also agree on the NO-LINE-BREAK argument :sweat_smile:    
(I must have fallen in an edge case with base64 encoding to get this error)

Anyway, thanks a lot for the quick fix and thanks a lot for the package that I can enjoy now :+1:

**Comment by fasheng** [comment]
Enjoy! :smile:
