### ISSUE TITLE
Allow to access articles by folder 

### ISSUE THREAD

**Issue by Kaligule** [fasheng/elfeed-protocol#32]
Thank you for this awesome effort of uniting so many protocols. I would never have considered using elfeed without this project.

I connected elfeed to newsblur and it seems like the articles fetched use the tags that the articles give themselfs. Unfortunatelly these tags tend to be unreliable (most sites don't use them or spam every article with as many tags as possible).

On the other hand, most servers allow their users to organize their feeds in folders. As the user does this for himself, this categorisation is often a better and more consistent.
It would be great if we could access the folder of the feed as a tag.

I have only played around with elfeed and elfeed protocol for a few hours, so perhaps there is a better way which I don't see. In this case I would be very glad to hear about it.

The folder of a feed in newsblur can be found using [/reader/feeds](https://www.newsblur.com/api#/reader/feeds).

**Comment by fasheng** [comment]
If you want split feeds with custom tags, please have a try `elfeed-org`. And there is example code in README about let `elfeed-org` work together with `elfeed-protocol`. Enjoy!

**Comment by Kaligule** [comment]
Do I understand correctly that this would mean I had to maintain the list and categorisation of my feeds in two places (in the org file and on the server)? Because this would be a very tedious and error prone setup.

I want the elfeed tags to mirror the already existing structure of feeds on the server.

**Comment by fasheng** [comment]
Well, I manage my feeds with elfeed-org and export/sync them to other places and just working fine.

About your request feature to convert remote folder/category to tags, I have to say there is currently not much motivation to implement it for me. Maybe someday I will consider this feature if have time, however before that, any PR is welcome.

**Comment by fasheng** [comment]
BTW, I use a custom function to filter feeds in elfeed, hope helpes:
https://github.com/skeeto/elfeed/issues/216

**Comment by Kaligule** [comment]
I see, thank you. Do I understand you correctly that in your setup you still have a single source of truth, but it is the org-file and not the server? Because this _would_ be a viable solution to my problem.

Could you explain a bit about what is synced with this setup? Is the headline-structure of the org-file translated to be the folder-structure on the server or something similar?

**Comment by fasheng** [comment]
Oh, I just mean export feeds to OPML file from elfeed-org, then import them to remote server manually.

**Comment by Kaligule** [comment]
I see. That won't work for me. For me the whole point of having a server is for it to syncronize feeds and the read-status of the articles. This way I can use different clients on different devices. Thank you nevertheless.

It looks like the functionality is just not there, currently. I think we should let this issue be for now until someone attacs it with code.

**Comment by lockywolf** [comment]
I would be using this too.

If I have time, I may try to implement this, but  that may never happen.

**Comment by fasheng** [comment]
Now all protocols support fetch remote category as tag, include newsblur, please try it.

**Comment by fasheng** [comment]
Finished, any question just report later.

**Comment by Kaligule** [comment]
@fasheng 

I stopped using Newsblur earlier this year. I just tried it for ttrss (should work the same way if I understand correctly).

This is __so__ _awesome_. Thank you.

This makes elfeed useful for me.
