### ISSUE TITLE
ttrss fetch all articles

### ISSUE THREAD

**Issue by KrullBorg** [fasheng/elfeed-protocol#43]
is there a way to fetch all articles from my tiny tiny rss server? (i have a lot of articles from 2009 to now)

the first time it fetches only 200 articles; then i tried many times with elfeed-protocol-ttrss-update, elfeed-protocol-ttrss-update-older and elfeed-protocol-ttrss-star but sometimes it downloads something and sometimes not

i have no starred article on my server

thanks in advance

**Comment by fasheng** [comment]
ttrss only allow fetch 200 articles one time, so you must run `elfeed-protocol-ttrss-update-older` multiple times to fetch more. It's just fine if do not return new articles sometimes for the article IDs is not continuous in ttrss.

And the update operations could not executed in the same time, so `run-at-time` with some delays will help you.

**Comment by fasheng** [comment]
Hi, I added some example code in commit https://github.com/fasheng/elfeed-protocol/commit/4a59e26216ceb6eb466781f15b6ac770b90437f6 just now. And this issue will be closed~
