### ISSUE TITLE
URL malformed. The syntax was not correct."

### ISSUE THREAD

**Issue by 404cn** [fasheng/elfeed-protocol#45]
- OS version: `9.4.4`
- emacs version: `28.0.50`
- elfeed version: `latest melpa version`
- elfeed-protocol version: `latest melpa version`
- curl version: `7.75.0`
- server version: `???` (docker image and tag)
- is variable `elfeed-protocol-fever-feeds` empty: `no`

**elfeed-log**

Please collect logs in buffer `*elfeed-log*` with the following config
before reporting issues:

`[2021-03-30 20:30:11] [error]: ?api&feeds: "(3) URL malformed. The syntax was not correct."`

```emacs-lisp
(setq elfeed-log-level 'debug)
(toggle-debug-on-error)

```
```
[2021-03-30 20:34:56] [debug]: elfeed-protocol-fever: update feed list
[2021-03-30 20:34:56] [debug]: retrieve (?api&feeds)
[2021-03-30 20:34:56] [error]: ?api&feeds: "(3) URL malformed. The syntax was not correct."
```

Example config:

```
(leaf elfeed-protocol
  :straight t
  :after elfeed
  :init
  (setq elfeed-protocol-fever-maxsize 1000)
  (setq elfeed-use-curl t)
  (elfeed-set-timeout 36000)
  (setq elfeed-curl-extra-arguments '("--insecure"))
  (setq elfeed-feeds '("fever+https://miniflux:miniflux@example.com/fever/"))
  (elfeed-protocol-enable))
```

**Comment by 404cn** [comment]
change config to :

```
 (setq elfeed-feeds (list
                      (list "fever+https://miniflux@example.com"
                            :api-url "https://example.com/fever/"
                            :password "miniflux"
                            :autotags '(("example.com" comic)))))
```

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  split-string(nil ",")
  elfeed-protocol-split-ids-sub-size("," nil 1000)
```

**Comment by 404cn** [comment]
elfeed-log: 

```
[2021-03-30 20:39:04] [debug]: elfeed-protocol-fever: update feed list
[2021-03-30 20:39:04] [debug]: retrieve (https://example.com/fever/?api&feeds)
[2021-03-30 20:39:05] [debug]: elfeed-protocol-fever: found 0 feeds
[2021-03-30 20:39:05] [debug]: elfeed-protocol-fever: update entries with action init, arg nil
[2021-03-30 20:39:05] [debug]: retrieve (https://example.com/fever/?api&saved_item_ids)

```

**Comment by 404cn** [comment]
Don't know why it says `found 0 feeds`, I use reeder on my phone with fever and it's work perfect.

**Comment by 404cn** [comment]
> I use miniflux+fever and similar config, too. Here is my environment:
> 
> * OS version: `nixos linux 5.4.100`
> * emacs version: `27.1`
> * elfeed version: `3.3.0`
> * elfeed-protocol version: `0.8.0`
> * curl version: `7.74.0`
> * server version: `miniflux/miniflux:2.0.20` (docker image and tag)
> 
> Please check if you could fetch feeds correctly in bash shell:
> 
> ```shell
> curl -H'User-Agent: Emacs Elfeed 3.3.0' -XPOST -d api_key=$(echo -n 'user:pass' | md5sum | awk '{print $1}') 'https://example.com/fever/?api&feeds'
> ```

Here is the output

`{"api_version":3,"auth":0,"last_refreshed_on_time":0}`

**Comment by 404cn** [comment]
> I use miniflux+fever and similar config, too. Here is my environment:
> 
> * OS version: `nixos linux 5.4.100`
> * emacs version: `27.1`
> * elfeed version: `3.3.0`
> * elfeed-protocol version: `0.8.0`
> * curl version: `7.74.0`
> * server version: `miniflux/miniflux:2.0.20` (docker image and tag)
> 
> Please check if you could fetch feeds correctly in bash shell:
> 
> ```shell
> curl -H'User-Agent: Emacs Elfeed 3.3.0' -XPOST -d api_key=$(echo -n 'user:pass' | md5sum | awk '{print $1}') 'https://example.com/fever/?api&feeds'
> ```

I fount it return `auth:0`, and yep, my username and password is wrong. Now it worked, sorry about mine... and thanks about your reply!

**Comment by fasheng** [comment]
Fine. Enjoy!
