### ISSUE TITLE
Nextcloud password read from shell is base64 encoded with a newline

### ISSUE THREAD

**Issue by apiraino** [fasheng/elfeed-protocol#48]
Hello,

when the password is read from a `shell-command-to-string` newlines still seems to be present. Example:

```
  (setq elfeed-feeds '(
                     ("owncloud+https://user@myhost.com"
                      :password (shell-command-to-string "pass logins/nextcloud | head -n1"))
```

Issue #30 leads me to a workaround to remove the newline when the base64 for authentication is created:
```
  (setq elfeed-feeds '(
                     ("owncloud+https://user@myhost.com"
                      :password (shell-command-to-string "echo -n `pass logins/nextcloud | head -n1`"))
```

I wonder if this is something `elfeed-protocol` should take care of, or my workaround is the correct fix.

Thank you for elfeed-protocol!!

System info:

- OS version: `debian`
- emacs version: `Doom emacs 28.0.50`
- elfeed version: https://github.com/skeeto/elfeed/commit/162d7d545ed41c27967d108c04aa31f5a61c8e16
- elfeed-protocol version: https://github.com/fasheng/elfeed-protocol/commit/5e17d4280f5f8019c3f8962a710c9b3e633f41ff
- curl version: `curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1l zlib/1.2.11 brotli/1.0.9 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3`
- server version: `nextcloud 21.0.4`
- is variable `elfeed-protocol-xxx-feeds` empty: (I don't understand what that means)

**Comment by fasheng** [comment]
Thanks your report. How about use `(password-store-get "logins/nextcloud")` instead?
I will update the demo code about `shell-command-to-string` as you did later.

**Comment by apiraino** [comment]
thank you for the quick reply. Your suggestion makes great sense but I prefer using the shell as I don't need to access often my keyring from emacs, therefore I don't have `password-store.el` installed.

thank you again for elfeed-protocol, it's a great addition to elfeed!
