### ISSUE TITLE
elfeed-protocol-fever.el has some flaws when synchronizing data

### ISSUE THREAD

**Issue by declanqian** [fasheng/elfeed-protocol#49]
Just self-hosted a miniflux instance. Was testing out the synchronization functionality across multi devices.
The initial synchronization is fine, and `elfeed-org` tag rules works as expected.
However elfeed-protocol-fever.el has some flaws synchronizing data  when

- items marked read on other devices, failed to remove local `unread` tag when using elfeed commands
- items removed from saved, failed to remove local `star` tag when using elfeed commands

Elfeed commands I've tried
- `elfeed-protocol-fever-reinit`
- `elfeed-protocol-fever-update`
- `elfeed-protocol-fever-update-star`

----
- OS version: `Darwin Declans-MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64`
- emacs version: `GNU Emacs 28.0.91 (build 2, x86_64-apple-darwin21.2.0, NS appkit-2113.20 Version 12.1 (Build 21C52)) of 2022-01-15`
- elfeed version: `3.4.1`
- elfeed-protocol version: `c88bb24`
- curl version:
```curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

- server version: `https://github.com/miniflux/v2/blob/50c5850f/contrib/docker-compose/basic.yml`
- is variable `elfeed-protocol-fever-feeds` empty: `no`

**elfeed-log**
There are no errors other than feed data, I am gonna omit this one.

**Comment by fasheng** [comment]
Sadly, if you want sync article stat in two-way from other client, there is no support in fever api level. However here is a workaround in #28. Hope helps.

**Comment by declanqian** [comment]
Oh, It's a known issue. I only read through the README, forgot to dig issues.
Thanks for pointing the workaround. Yeah, it works. Good enough for me now.
