### ISSUE TITLE
Provide an option to opt-out protocols

### ISSUE THREAD

**Issue by declanqian** [fasheng/elfeed-protocol#50]
Right now, we require all [protocols](https://github.com/fasheng/elfeed-protocol/blob/master/elfeed-protocol.el#L60-L63) here. This catch my eyes on cause when I do `M-x elfeed-protoco`, there are some candidates I would never use...

Provide a way to use only needed ones. Maybe like the way `C-h v org-modules` did it?
For compatibility, we can set default to all protocols. As a user, I can opt-out some to only the ones I needed.

This is a feature request.

**Comment by fasheng** [comment]
Fine, I will try to improve it later~
