### ISSUE TITLE
fever update to accomodate id generation by freshrss

### ISSUE THREAD

**Issue by CosmosAtlas** [fasheng/elfeed-protocol#53]
- OS version: NA
- emacs version: NA
- elfeed version: NA
- elfeed-protocol version: `eaf1329ff221098eb6d4709245010d070c89b173`
- curl version: NA
- server version: `(https://hub.docker.com/r/linuxserver/freshrss)` (docker image and tag)
- is variable `elfeed-protocol-xxx-feeds` empty: `no`

**elfeed-log**

NA

**error backtrace**

NA

## Behavior

When currently using a fever feed from FreshRss, `update` won't show new items.

## Root cause

Upon inspection, `elfeed-protocol-fever-update` basically just fetches 50 new entries based on the `last-entry-id`. However, FreshRss generates its id by Unix time ([some irrelevant discussion here](https://github.com/FreshRSS/FreshRSS/issues/2273), but covers how the id is implemented).

So it means that, realistically, the update function will never generate new entry ids (given it only generates ids within 50/1000 of a second...)

## Suggested fix

I'm not familiar with elisp enough to fix this personally, but below are some highlevel ideas.

* Use the fever [unread_item_ids](https://freshrss.example.net/api/fever.php?api&unread_item_ids) as used in `init`

## Side Note

With `unread_item_ids` from fever, it would be possible to match with local database, so that read status can be synced the other way around as requested by #38 . Meaning that if a current unread item doesn't exists in fever's new `unread_item_ids` it can be marked as read.

**Comment by fasheng** [comment]
Thanks for your report. Here is a workaround for it, if works, just close the issue:
```lisp
(setq elfeed-protocol-fever-update-unread-only t)
```

**Comment by CosmosAtlas** [comment]
Can confirm the work around works for me. Thank you for the quick response!
