### ISSUE TITLE
elfeed protocol fails to connect with bazqux.com with fever api

### ISSUE THREAD

**Issue by pirattidasan** [fasheng/elfeed-protocol#57]
- OS version: `Arch Linux x86_64 Kernel 6.2.9`
- emacs version: `28.2`
- elfeed version: `3.4.1`
- elfeed-protocol version: `0.3.2`
- curl version: `8.0.1`
- is variable `elfeed-protocol-fever-feeds` empty: `yes`

**elfeed-log**
[2023-04-08 18:58:04] [debug]: retrieve (https://bazqux.com/fever/?api&feeds)
[2023-04-08 18:58:05] [debug]: elfeed-protocol-fever: {"api_version":3,"auth":0}
[2023-04-08 18:58:05] [error]: elfeed-protocol-fever: authentication failed, wrong username or password

bazqux.com has a fever api which works with simple curl authentication. It has the following format 

`user: email@somedomain` 
`password: somepassword` 

An md5sum of `user:password` works fine with `curl` authentication, but *only using the email* as username.  

The same fails in using elfeed protocol 
```emacs-lisp
    (setq elfeed-feeds (list
                        (list "fever+https://user@somedomain@bazqux.com"
                              :api-url "https://bazqux.com/fever/"
                              :password "somepassword")))
```

**Comment by fasheng** [comment]
I see, so your username contains `@` and `url-generic-parse-url` could not parse it correctly. I will try to solved it, later.
```elisp
(url-generic-parse-url "fever+https://user@somedomain@bazqux.com")
```

https://github.com/fasheng/elfeed-protocol/blob/master/elfeed-protocol-common.el#L139

**Comment by fasheng** [comment]
@pirattidasan I give a workaround for such issue, please test if working for bazqux.com.

**Comment by pirattidasan** [comment]
Works great ! Thank you.

**Comment by bordusko** [comment]
Hi, I'm trying to config elfeed-protocol with BazQux using Fever API, and I still get the authentication problem.

Here is my config:

```
(use-package elfeed
  :ensure t)
(use-package elfeed-protocol
  :ensure t)

(setq elfeed-log-level 'debug)
(setq elfeed-use-curl t)
(elfeed-set-timeout 36000)

(setq elfeed-protocol-fever-update-unread-only t)
(setq elfeed-protocol-fever-fetch-category-as-tag nil)
(setq elfeed-protocol-feeds '(("fever+https://user@somain.com@bazqux.com"
                               :api-url "https://bazqux.com/fever/"
                               :password "MD5_API_KEY")))

(setq elfeed-protocol-enabled-protocols '(fever))
(elfeed-protocol-enable)
```

Elfeed log:
```
[debug]: elfeed-protocol-fever: update feed list
[debug]: retrieve (https://bazqux.com/fever/?api&feeds)
[error]: elfeed-protocol-fever: authentication failed, wrong username or password
```
The same credentials works fine with curl authentication:
`curl -s -F "api_key=MD5_API_KEY" 'https://bazqux.com/fever/?api&feeds'`

**Comment by fasheng** [comment]
@bordusko Which elfeed-protocol version do you use? This issue should be solved and the issue creator confirmed it.

**Comment by bordusko** [comment]
I'm using:
elfeed-protocol: 20240822.805
elfeed: 20241202.22

Maybe I will also have a try at Bazqux support.

**Comment by fasheng** [comment]
Looks the `:password` field should be your real password instead of `MD5_API_KEY`. elfeed-protocol-fever will calculate the md5 value itself.

https://github.com/fasheng/elfeed-protocol/blob/master/elfeed-protocol-fever.el#L87C24-L87C24

**Comment by bordusko** [comment]
> Looks the `:password` field should be your real password instead of `MD5_API_KEY`. elfeed-protocol-fever will calculate the md5 value itself.
> 
> https://github.com/fasheng/elfeed-protocol/blob/master/elfeed-protocol-fever.el#L87C24-L87C24

Yeah, silly me, I was trying that in my config this way:
`:password "email:password"`

instead of:
`:password "password"`

Thank you very much.
