### ISSUE TITLE
Missing author due to elfeed meta key change

### ISSUE THREAD

**Issue by akurth** [fasheng/elfeed-protocol#58]
- OS version: Linux
- emacs version: 29
- elfeed version: 20210822.2129
- elfeed-protocol version: 20230413.443
- curl version: 7.88.1
- server version: NextCloud 26.0.1
- is variable `elfeed-protocol-owncloud-feeds` empty: no

Due to [this elfeed change](https://github.com/skeeto/elfeed/commit/99855cf145084811c5ad90c2b45ea16b9dccd7e3) the author field is not displayed by elfeed when fetching the data by elfeed-protocol. Elfeed expects the key `:authors ((:name "John Doe"))`, but seems to get `:author "John Doe"` from elfeed-protocol.

**Comment by fasheng** [comment]
Thanks for the report. It should be solved now. Please have a try.

**Comment by akurth** [comment]
Wow, that was fast. Thank you very much!
