### ISSUE TITLE
assignment to free variable 'elfeed-protocol-tags'

### ISSUE THREAD

**Issue by bsvh** [fasheng/elfeed-protocol#59]
- OS version: `Debian 12`
- emacs version: `29.1.50`
- elfeed version: `20221108.755`
- elfeed-protocol version: `20230512.950`

I'm using the following snippet from the README in my init.el:

```
(defadvice elfeed (after configure-elfeed-feeds activate)
  "Make elfeed-org autotags rules works with elfeed-protocol."
  (setq elfeed-protocol-tags elfeed-feeds)
  (setq elfeed-feeds (list
                      (list "owncloud+https://user@myhost.com"
                            :password '(password-store-get "owncloud/app-pass")
                            :autotags elfeed-protocol-tags))))
```

This results in a bytecompile warning when launching emacs.

**error backtrace**

```
Warning (bytecomp): assignment to free variable ‘elfeed-protocol-tags’
Warning (bytecomp): reference to free variable ‘elfeed-protocol-tags’
```

The `elfeed-protocol-tags` variable does not seem to be present in any of the source file in the repository. Is the snippet still relevant?

**Comment by fasheng** [comment]
Yes, `elfeed-protocol-tags` is just a temp variable in the example snippet, you can use any variable instead to store `elfeed-feeds` here.

**Comment by bsvh** [comment]
Ok. When installing `elfeed-protocol` with `use-package`, the bytecomp warning appears every time I open emacs. I was able to silence the error by adding a `(setq elfeed-protocol-tags nil)` before the `defadvice`.

**Comment by fasheng** [comment]
I will update the example code later
```elisp
(defvar elfeed-protocol-orig-feeds nil
  "Store original content of `elfeed-feeds'.")
(defadvice elfeed (after configure-elfeed-feeds activate)
  "Make elfeed-org autotags rules works with elfeed-protocol."
  (setq elfeed-protocol-orig-feeds elfeed-feeds)
  (setq elfeed-feeds (list
                      (list "owncloud+https://user@myhost.com"
                            :password '(password-store-get "owncloud/app-pass")
                            :autotags elfeed-protocol-orig-feeds))))
```
