### ISSUE TITLE
Help with fetching starred entries and adding starred entries on FreshRSS using Fever

### ISSUE THREAD

**Issue by bmp** [fasheng/elfeed-protocol#62]
Does Elfeed protocol allow for,
1. Fetching starred entries from a FreshRSS instance?
2. Adding starred entried back into the FreshRSS instance?

Starred entries are called favourites in FreshRSS if that helps!

Apologies,  I was unable to find any documentation about this.

**Comment by fasheng** [comment]
Yes, both will work with fever API.

**Comment by bmp** [comment]
That is great! Are there any pointers to how I can do this? Or if elfeed already implement this? Any suggestions would be great.

**Comment by fasheng** [comment]
First you should get your freshrss's fever api url, then just follow the example steps in README:
https://github.com/fasheng/elfeed-protocol#fever-fever

**Comment by bmp** [comment]
Thank you!
