### ISSUE TITLE
Support for Omnivore

### ISSUE THREAD

**Issue by edmundmiller** [fasheng/elfeed-protocol#64]
I was thinking about making a seperate Emacs package for [Omnivore](https://omnivore.app/), but I think making an elfeed-protocol would be a better concept! 

I don't know if I'll get to it, so I just thought I'd put the idea out there.

**Comment by fasheng** [comment]
I'm not familiar with Omnivore, looks it's not a RSS service. However, if it provide API to fetch articles, and we can track the updating state with for example the article id or the modified timestamp, then you can try to implement it with elfeed-protocol. Any question or PRs are welcome here :)

**Comment by dertuxmalwieder** [comment]
As Omnivore is being sunset, this is probably WONTFIX now?

**Comment by fasheng** [comment]
Read-it-later service's API is not similar with RSS service. So this is not a high priority feature for elfeed-protocol. Besides, I suggest use `wallabag` instead which provide RSS feeds.

**Comment by dertuxmalwieder** [comment]
I know. I think there was a misunderstanding here: I *suggested* to just close this issue, as Omnivore (which supports RSS feeds as well) will be [shut down](https://blog.omnivore.app/p/details-on-omnivore-shutting-down) soon, so elfeed supporting it won't make any sense anymore anyway. :-)

**Comment by fasheng** [comment]
I see, thanks for your reminder.
