### ISSUE TITLE
Does elfeed-protocol-feeds replace elfeed-feeds?

### ISSUE THREAD

**Issue by ckeschnat** [fasheng/elfeed-protocol#65]
Hello,
when using both `elfeed-protocol-feeds` and `elfeed-feeds`, `elfeed-feeds` is ignored. So I assume `elfeed-protocol-feeds` replaces it?

PS: I am a new elfeed user, meaning I did not use elfeed before 0.9.0 when `elfeed-protocol-feeds` was introduced (?), so I had no elfeed setup before that.

Thanks

**Comment by fasheng** [comment]
Yes, since version 0.9.0 , elfeed-protocol use variable elfeed-protocol-feeds instead of elfeed-feeds to fix conflict issues to extensions that modify or require elfeed-feeds, such as elfeed-org, elfeed-summary.

If you dont' use elfeed before, just keep `elfeed-feeds` empty and setup `elfeed-protocol-feeds` only.

**Comment by ckeschnat** [comment]
Cool, thanks. Older users should then migrate their feeds over from `elfeed-feeds` to `elfeed-protocol-feeds`, right? If so I will make a PR for the readme to make this clearer.

**Comment by fasheng** [comment]
Fine, welcome your PR. There is a NOTE in readme, but it looks not too eye-catching.

**Comment by fasheng** [comment]
I convert the old migrating note to important note, looks eye-catching now ;)

**Comment by ckeschnat** [comment]
Ok, cool :) Although I now noticed that it doesn't seem to be a drop-in replacement, e.g. autotags don't work anymore. Maybe that is specific to me and I don't want to take any more of your time. Thanks for this package, I will figure everything out in time. This issue can be closed I think.

**Comment by fasheng** [comment]
You mean original `:autotags` syntax in elfeed-feeds/elfeed-protocol-feeds? It still works, however use elfeed-org is a better choice.

OK, I will close the issue. Enjoy!

**Comment by ckeschnat** [comment]
Hi,
I meant e.g. the `xah` in this example:

```
(setq elfeed-protocol-feeds
            '(("ttrss+https://me@ttrss.mysite"
               :password (password-store-get "ttrss.mysite/me"))
              ("https://www.youtube.com/feeds/videos.xml?channel_id=UCXEJNKH9I4xsoyUNN3IL96A" xah)))
```

Worked with `elfeed-feeds`, does not work with `elfeed-protocol-feeds`.

**Comment by fasheng** [comment]
I see, there is two solutions:
1. copy the youtube feed to :autotags field
    ```elisp
    (setq elfeed-protocol-feeds
          '(("ttrss+https://me@ttrss.mysite"
             :password (password-store-get "ttrss.mysite/me")
             :autotags (("https://www.youtube.com/feeds/videos.xml?channel_id=UCXEJNKH9I4xsoyUNN3IL96A" xah)))
            ("https://www.youtube.com/feeds/videos.xml?channel_id=UCXEJNKH9I4xsoyUNN3IL96A" xah)))
    ```
1. copy the youtube feed to `elfeed-feeds`, if there are many feeds, just use following config:
    ```elisp
    (setq elfeed-feeds '(("https://www.youtube.com/feeds/videos.xml?channel_id=UCXEJNKH9I4xsoyUNN3IL96A" xah)))
    (setq elfeed-protocol-feeds '(("ttrss+https://me@ttrss.mysite"
                                   :password (password-store-get "ttrss.mysite/me"))))
    (setq elfeed-protocol-feeds (append elfeed-protocol-feeds elfeed-feeds))
    ```

**Comment by ckeschnat** [comment]
Oooh, thanks so much. I just tried 2. and it works perfectly :)

Maybe this is something for the readme?

**Comment by fasheng** [comment]
You are right, the example code was added to README now.
