### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by NatHarari** [fasheng/elfeed-protocol#66]
- OS version: `MacOS 14.1`
- emacs version: `30.0.5`
- elfeed version: `2221108.755`
- elfeed-protocol version: `20231007.1535`
- curl version: `8.4.0`
- server version: `1.22.1-dev` (docker image and tag) FreshRSS
- is variable `elfeed-protocol-xxx-feeds` empty: `yes` elfeed-protocol-feeds is nil

**elfeed-log**
`[2023-10-30 19:17:23] [info]: Elfeed update: October 30 2023 19:17:23 CET
[2023-10-30 19:17:23] [warn]: elfeed-protocol: elfeed-protocol-feeds is empty, please setup it instead of elfeed-feeds since 0.9.0`

Please collect logs in buffer `*elfeed-log*` with the following config
before reporting issues:

```emacs-lisp
(setq elfeed-log-level 'debug)
(toggle-debug-on-error)

;; for more logs if necessary
(setq elfeed-protocol-log-trace t)
(setq elfeed-protocol-fever-maxsize 5)
(setq elfeed-protocol-owncloud-maxsize 5)
(setq elfeed-protocol-ttrss-maxsize 5)
(setq elfeed-protocol-newsblur-maxpages 1)
```

**error backtrace**

```
No errors except the one cited above
```

I cannot seem to connect to my FreshRSS feed. I just set it up today. I thought it might be an error with my FreshRSS installation, however, I used the same setup with Reeder on my iPad to test it. Same URL, same login/password, and it works perfectly. I thought it might be an https issue since I'm using http, but again: Reeder works fine. So maybe it's in my elisp? Here is my elisp:

  (use-package elfeed
    :bind
    ("C-x e" . elfeed))

  (require 'elfeed-goodies)

  (use-package elfeed-protocol
    :ensure t
    :demand t
    :after elfeed
    :config
    (elfeed-protocol-enable)
    :custom
    (elfeed-use-curl t)
    (elfeed-set-timeout 36000)
    (elfeed-log-level 'debug)
    (toggle-debug-on-error)
    (elfeed-curl-extra-arguments '("--insecure"))
    (setq elfeed-protocol-fever-update-unread-only t)
    (setq elfeed-protocol-fever-fetch-category-as-tag t)
    (setq elfeed-protocol-feeds '(("fever+http://username@mydomain.duckdns.org"
                                   :api-url "http://mydomain.duckdns.org/api/fever.php"
                                   :password "myAPIpassword"))))

**Comment by fasheng** [comment]
Just put `(setq elfeed-protocol-feeds ...` into `:config` section instead of `:cusotm`.

**Comment by NatHarari** [comment]
I got it, thanks. It was something else. I had to have the following in the top section before the elfeed-protocol bit:
    (elfeed-db-directory (locate-user-emacs-file "elfeed")))
Which I didn't have. Putting that there fixed it.

**Comment by fasheng** [comment]
Fine.
