### ISSUE TITLE
Typo in debug message

### ISSUE THREAD

**Issue by bmp** [fasheng/elfeed-protocol#69]
- OS version: `openSUSE Tumbleweed 20240605 x86_64`
- emacs version: `GNU Emacs 29.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0) of 2024-04-03`
- elfeed version: `3.4.1 5c05a1e`
- elfeed-protocol version: `0.3.2 9b2612d`
- curl version: `8.8.0 (x86_64-suse-linux-gnu)`
- server version: `1.24.0` (docker image and tag) on Yunohost
- is variable `elfeed-protocol-xxx-feeds` empty: `no`

When I check the elfeed-logs, I see the following message,

```
[2024-06-09 18:30:42] [info]: Elfeed update: June  9 2024 18:30:42 IST
[2024-06-09 18:30:42] [debug]: elfeed-protocol-fever: update feed list
[2024-06-09 18:30:42] [debug]: elfeed-protocol-fever: update cagetory list
```

There seems to be a typo at https://github.com/fasheng/elfeed-protocol/blob/9b2612da3e39d0832f98d376717a92c77594fbfc/elfeed-protocol-fever.el#L169 in the debug message.

**Comment by fasheng** [comment]
Thanks!
