### ISSUE TITLE
Can't get it to work with Nextcloud

### ISSUE THREAD

**Issue by jbz-dev** [fasheng/elfeed-protocol#9]
Hi,

Just tried your `elfeed-protocol` package with my Nextcloud instance and can't find how it work.

I installed `elfeed-protocol` and configured it.
When I launch `M+x elfeed` I try `M+x elfeed-protocol-owncloud-update` and then the minibuffer prompts `Protocol Feed:`.

What am I suppose to type there ?

Thanks

**Comment by fasheng** [comment]
I use nextcloud news everyday, so it really works.
You don't need to run `elfeed-protocol-owncloud-update` manually, just press `G` to fetch articles in elfeed search view like usual.

**Comment by Bridouz** [comment]
I ran the followings code and debug was :  

```
;; format 1
Debugger entered--Lisp error: (void-variable owncloud+https://justin:a5kueeNXT!\?)
  eval(owncloud+https://justin:a5kueeNXT!\? nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

;; format 2

Unvalid function
```

My password has ! and ? in it, maybe it can cause some issues ?

**Comment by fasheng** [comment]
Yes, so just use format 2, and delete your secret info in past comment ;)

**Comment by fasheng** [comment]
Oh, format 2 show 'Unvalid function'... What that mean?

**Comment by fasheng** [comment]
I guess format 2 should works for you, please have a try.

**Comment by fasheng** [comment]
emmm, your error looks strange.. Please ensure `(elfeed-protocol-enable)` before such test:

```lisp
;; prefer result: "owncloud+https://raspbridouz.duckdns.org/nextcloud"
(let* ((elfeed-feeds '(("owncloud+https://username@raspbridouz.duckdns.org/nextcloud" :password "password:!\?"))))
  (elfeed-protocol-no-auth-url (nth 0 (elfeed-protocol-feed-list))))
```
I just think it's really easy.

**Comment by fasheng** [comment]
Maybe we should skip such testing in scratch. Believe me, use format 2 in your `elfeed-feeds` settings and everything will be fine.
